version: '3.8'

services:
  frontend:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger
    ports:
      - "8000:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yml
    volumes:
      - ./openapi/api:/aos/:ro
    depends_on:
      - api
  api:
    build: .
    container_name: grupo6aos_api_gestion_clientes
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - gestion-clientes-data:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion-clientes

volumes:
  gestion-clientes-data: