apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui
          ports:
            - containerPort: 8080
          env:
            - name: SWAGGER_JSON
              value: /usr/share/nginx/html/openapi/openapi.yml
          volumeMounts:
            - name: openapi-volume
              mountPath: /usr/share/nginx/html/openapi
              readOnly: true
      volumes:
        - name: openapi-volume
          configMap:
            name: openapi-config
