apiVersion: v1
kind: Service
metadata:
  name: api-gestion-clientes-service
spec:
  selector:
    app: api-gestion-clientes
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort